fix: fix bytes abi transformation
nervosnetwork/polyjuice-provider pull request #89
Opened 2022-01-23 20:10 UTC by Kuzirashi

Related to: https://github.com/nervosnetwork/polyjuice-provider/issues/88

2022-01-24 05:09 UTC, RetricSu commented
please fix ci @Kuzirashi

2022-01-24 13:19 UTC, Kuzirashi commented
Fixed @RetricSu

2022-01-25 03:59 UTC, RetricSu commented on packages/base/src/abi.ts
> +      value: parsedParam === null ? "0x" : parsedParam,
I give it some thoughts. the problem is that one of provider dependencies library `web3-eth-abi` treat `0x` for type `bytes` as null when decoding parameters https://github.com/nervosnetwork/polyjuice-provider/blob/main/packages/base/src/abi.ts#L221-L224 , 
and the problem only happens to bytes, not even bytes2 / bytes8 / ... bytes32.

simply add `parsedParam === null ? "0x" : parsedParam` might not be the best choice.  instead, we can add `const isBytes = abiItem.inputs[i].type.indexOf("bytes") === 0; ` here https://github.com/nervosnetwork/polyjuice-provider/blob/main/packages/base/src/abi.ts#L235, and check if bytes type value is null, if so, replace with 0x

2022-01-25 04:02 UTC, RetricSu requested changes
I give it some thoughts. the problem is that one of provider dependencies library `web3-eth-abi` treat `0x` for type `bytes` as `null` when [decoding parameters](https://github.com/nervosnetwork/polyjuice-provider/blob/main/packages/base/src/abi.ts#L221-L224) , and the problem only happens to bytes, not even bytes2 / bytes8 / ... bytes32.

simply add `parsedParam === null ? "0x" : parsedParam` might not be the best choice.  instead, we can add `const isBytes = abiItem.inputs[i].type.indexOf("bytes") === 0; ` [here](https://github.com/nervosnetwork/polyjuice-provider/blob/main/packages/base/src/abi.ts#L235), and check if bytes type value is null, if so, replace with 0x

2022-01-27 23:00 UTC, Kuzirashi commented
Can you check again @RetricSu ?

2022-01-28 01:47 UTC, RetricSu approved these changes

2022-01-28 01:48 UTC, merged